// Generated by Wrangler by running `wrangler types`

interface Env {
	JWT_SECRET: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_BUCKET_NAME: string;
	R2_BUCKET: R2Bucket;
	DB: D1Database;
}
